version: '3.8'
services:
  ninja-wallet:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ninja_wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
